export const CONFIG = {
  collections: {
    CHESHBONIT: 'CHESHBONIT',
    MUCARIM: 'MUCARIM',
    SHARATIM: 'SHARATIM',
    YADANIIM: 'YADANIIM',
    GY: 'GY',
    HASAOT: 'HASAOT',
    HASNET: 'HASNET',
    HASMASLULIM: 'HASMASLULIM',
    MISROT: 'MISROT',
    MISROTGY: 'MISROTGY',
    MOADON: 'MOADON',
    MUTAVIM: 'MUTAVIM',
    SHEFI: 'SHEFI',
    NOSEME: 'NOSEME',
    MOSDOT: 'MOSDOT',
    RUNS: 'runs',
    COMMANDS: 'COMMANDS',
    RUN_LOGS: 'run_logs',
    RUN_RESULTS: 'run_results',
    RUN_HASHVHA: 'run_hashvha',
    USERS: 'USERS',
  } as Record<string, string>,
};
